/**
 * Markdown → HTML rendering (GFM tables, math, highlighted code).
 *
 * Math is validated with KaTeX at build time but stored as compact
 * placeholders (`<span class="math-tex" data-display="…">tex</span>`);
 * `hydrateMath()` (src/lib/content/math.ts) turns them into KaTeX markup on
 * the server (SSR) or in the browser. Pre-rendered KaTeX HTML is ~15× larger
 * than its source, so storing it would bloat the content bundle.
 *
 * Raw HTML in Markdown is NOT passed through, so output only contains markup
 * generated by this trusted pipeline.
 */
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import remarkRehype from "remark-rehype";
import rehypeHighlight from "rehype-highlight";
import rehypeStringify from "rehype-stringify";
import katex from "katex";
import type { Root, Element, ElementContent } from "hast";
import { visit, SKIP } from "unist-util-visit";

export interface RenderResult {
  html: string;
  errors: string[];
}

function textOf(node: Element): string {
  let s = "";
  for (const c of node.children as ElementContent[]) {
    if (c.type === "text") s += c.value;
    else if (c.type === "element") s += textOf(c);
  }
  return s;
}

/** Replace remark-math's <code class="language-math"> nodes with placeholders, validating with KaTeX. */
function rehypeMathPlaceholders(errors: string[]) {
  return () => (tree: Root) => {
    visit(tree, "element", (node: Element, index, parent) => {
      if (!parent || index === undefined) return;
      const cls = (node.properties?.className as string[] | undefined) ?? [];
      // Display math arrives as <pre><code class="language-math math-display">
      if (node.tagName === "pre" && node.children.length === 1) {
        const child = node.children[0];
        if (child.type === "element" && child.tagName === "code") {
          const ccls = (child.properties?.className as string[] | undefined) ?? [];
          if (ccls.includes("math-display")) {
            const tex = textOf(child);
            check(tex, true, errors);
            (parent.children as ElementContent[])[index] = placeholder(tex, true);
            return SKIP;
          }
        }
      }
      if (node.tagName === "code" && (cls.includes("math-inline") || cls.includes("math-display"))) {
        const display = cls.includes("math-display");
        const tex = textOf(node);
        check(tex, display, errors);
        (parent.children as ElementContent[])[index] = placeholder(tex, display);
        return SKIP;
      }
    });
  };
}

function placeholder(tex: string, display: boolean): Element {
  return {
    type: "element",
    tagName: display ? "div" : "span",
    properties: { className: ["math-tex"], dataDisplay: display ? "true" : "false" },
    children: [{ type: "text", value: tex }],
  };
}

function check(tex: string, displayMode: boolean, errors: string[]) {
  try {
    katex.renderToString(tex, { displayMode, throwOnError: true, strict: "ignore" });
  } catch (e) {
    errors.push(`KaTeX: ${(e as Error).message.split("\n")[0]} in "${tex.slice(0, 80)}"`);
  }
}

// Processing is synchronous, so a module-level error sink reset per call is safe.
const sink: string[] = [];
const processor = unified()
  .use(remarkParse)
  .use(remarkGfm)
  .use(remarkMath)
  .use(remarkRehype)
  .use(rehypeMathPlaceholders(sink))
  .use(rehypeHighlight, { detect: false })
  .use(rehypeStringify)
  .freeze();

export function renderMarkdown(md: string): RenderResult {
  sink.length = 0;
  let html = String(processor.processSync(md));
  const errors = [...sink];
  html = html.replace(/<img /g, '<img loading="lazy" decoding="async" ');
  html = html.replace(/<table>/g, '<div class="table-wrap"><table>').replace(/<\/table>/g, "</table></div>");
  return { html, errors };
}

/** Render a LaTeX expression in display mode (used for formula cards). */
export function renderDisplayMath(latex: string): RenderResult {
  return renderMarkdown(`$$\n${latex}\n$$`);
}

/** Strip Markdown/LaTeX to plain text for search indexing and previews. */
export function markdownToPlain(md: string): string {
  return md
    .replace(/```[\s\S]*?```/g, (m) => m.replace(/```\w*/g, " "))
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\$\$?([^$]*)\$\$?/g, (_m, inner: string) =>
      inner
        .replace(/\\(frac|dfrac|tfrac)\{([^}]*)\}\{([^}]*)\}/g, "$2/$3")
        .replace(/\\(mathbb|mathbf|mathrm|text|operatorname)\{([^}]*)\}/g, "$2")
        .replace(/\\([a-zA-Z]+)/g, "$1")
        .replace(/[{}]/g, ""),
    )
    .replace(/[*_`#>|]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
